# Site settings
title: Chris Cantimbuhan
email: chriscantimbuhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chriscantimbuhan.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: "chriscantimbuhan"

# Build settings
markdown: kramdown
